name: Generate shadowrocket rules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  build_rules_list:
    runs-on: ubuntu-latest
    steps:
      - name: Generate domain_custom.list file
        run: |
          curl -sSL https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/main/custom.list \
          | sed -E 's/^\+\./DOMAIN-SUFFIX,/; s/^[^D]/DOMAIN-SUFFIX,&/' > domain_custom.list
          
      - name: Generate domain_antifilter.list file
        run: |
          curl -sSL https://community.antifilter.download/list/domains.lst \
          | sed -E 's/^\+\./DOMAIN-SUFFIX,/; s/^[^D]/DOMAIN-SUFFIX,&/' > domain_antifilter.list

      - name: Generate geoip_antifilter.list file
        run: |
          curl -sSL https://community.antifilter.download/list/community.lst | sed 's/^/IP-CIDR,/' > geoip_antifilter.list       

      - name: Move files to rules directory
        run: |
          mkdir -p rules.d
          cp *.list ./rules.d/

      - name: Upload rule list artifact
        uses: actions/upload-artifact@v4
        with:
          name: rules
          path: ./rules.d/

  build_Shadowrocket_conf_file:
    runs-on: ubuntu-latest
    needs: build_rules_list
    steps:
      - name: Creating Folders
        run: |
          mkdir -p conf.d
          
      - name: Get common configuration files
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: 'Custom'
          token: ${{ secrets.ACCESS_TOKEN }}
          sparse-checkout: |
            General.txt
          sparse-checkout-cone-mode: false
          path: conf.d

      - name: Concatenate rule configuration files
        run: |
          cat <<EOF >> ./conf.d/General.txt
          [Rule]
          RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/release/rules/domain_custom.list,PROXY
          RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/release/rules/domain_antifilter.list,AUTO

          RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/release/rules/geoip_antifilter.list,AUTO,no-resolve
          FINAL,AUTO
          
          EOF

      - name: Concatenate All configuration file
        run: |
          cat ./conf.d/*.txt > ./conf.d/Shadowrocket.conf
          sed -i "1s/^/# Built on $(TZ="Asia/Novokuznetsk" date)\n/" ./conf.d/Shadowrocket.conf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: conf
          path: ./conf.d/Shadowrocket.conf
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: [build_rules_list,build_Shadowrocket_conf_file]
    steps:     
      - name: Configure variable names
        run: |
          echo "release_NAME=Built on $(TZ="Asia/Novokuznetsk" date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(TZ="Asia/Novokuznetsk" date +%Y%m%d%H%M)" >> $GITHUB_ENV
          mkdir -p rules

      - name: Download artifact 
        uses: actions/download-artifact@v4
        with:
          path: ./rules

      - name: Publish and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.release_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./rules/*
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Upload artifact to "release" branch
        run: |
          cd rules || exit 1
          ggit init --initial-branch=release
          git config --local user.name ${{ secrets.USER_NAME }}
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git init -b release
          git add .
          git commit -m "${{ env.release_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
          # git push --delete origin $( git ls-remote --tags origin | awk '{print $2}' | grep -vE "$(echo -e ${TAG_NAME})")
          
      - name: Purge jsdelivr CDN
        run: |
          cd rules || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done

  Delete_Historical_Data:
    runs-on: ubuntu-latest
    needs: publish
    steps:
        - name: Delete old artifacts
          uses: geekyeggo/delete-artifact@v5
          with:
            name: |
                rules
                conf

        - name: Delete old tags and releases
          uses: dev-drprasad/delete-older-releases@v0.3.4
          with:
            keep_latest: 3
            delete_expired_data: 7
            delete_tags: true
          env:
              GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

        - name: Delete old workflow runs
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ secrets.ACCESS_TOKEN }}
            repository: ${{ github.repository }}
            retain_days: 7
            keep_minimum_runs: 3
          
    
